### PR TITLE
Move classes to support.design.widget package..

### PR DESCRIPTION
**Pull request by timusus**
By using the same package name as the original `CollapsingToolbarLayout` class, we can also access protected classes from that package, which means we don’t need to duplicate all the helper classes.

This change moves `SubtitleCollapsingTextHelper` and `SubtitleCollapsingToolbarLayout` to `android.support.design.widget`, and removes all of the now-redundant helper classes.

Also removed the now unused srcDirs from the build.gradle file.

### CODE REVIEW

**Comment by timusus** [comment]
533f60d resolves #2.

**Comment by HendraAnggrian** [comment]
But if we move the package to `android.support.design.widget`, don't you think future version of support design could potentially break the library?

I'm really just concerned about compatibility, if you think there will be no significant issue I'm also for reusing those protected helper classes instead of duplicating them.

**Comment by timusus** [comment]
I don't really have a good answer for you, that's a valid question.

But, you're compiling against a specific version of the support design library, defined in your build.gradle. In order for your library to break, the design support library would need to change in some incompatible way, _and_ you would have to update the dependency to point to that new version of the design support library. 

If you're updating dependencies, you need to test for compatibility anyway. And your library might break regardless. So, I don't think it's a significant issue or a good reason to duplicate all those classes.

**Comment by HendraAnggrian** [comment]
Sorry for late response. I agree, I need to test for compatibility anyway. But I wanna make it clear that I'm probably only concerned about the newest support design library. If a newer support library has been released and this lib is incompatible with it, I will fix it without any regard that it might break older support library.

Anyway, thank you for your thought and work!

**Comment by timusus** [comment]
No worries. I think that's fair, you're not expected to maintain compatibility with all versions of the support library.

**Pull request merged**
